<?php


/**
 * Skeleton subclass for representing a row from the 'blog_article' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/19/10 10:43:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Article extends BaseArticle {
	
public function getNbComments()
{
  return $this->countComments();
}


public function getSummary(){
        $maxLen=20;
        $str=$this->getContent();
        if(strlen($str)>$maxLen)
            return substr($str,0,$maxLen)."...";
        else
            return $str;
    }

} // Article
