<?php


/**
 * Skeleton subclass for performing query and update operations on the 'blog_article' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/19/10 10:43:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ArticlePeer extends BaseArticlePeer {
	
	static function getComments($id)
	{
		$c=new Criteria();
       // $c->addByColumn('created_at');
        $c->add(CommentPeer::ARTICLE_ID, $id);
        
         return CommentPeer::doSelect($c);
	
	}
	
	
static function getArticle($id)
	{
		$c=new Criteria();
        $c->add(ArticlePeer::ID, $id);
        return ArticlePeer::doSelectOne($c);
	
	}
	
} // ArticlePeer
