package invention;

// Generated Jul 31, 2012 6:27:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import user.User;
import util.TableRowRepresentation;

/**
 * InventionFileEdition generated by hbm2java
 */
@Entity
@Table(name = "invention_file_edition", catalog = "patentsys")
public class InventionFileEdition implements java.io.Serializable , TableRowRepresentation{

	private int id;
	private User editor;
	private InventionFile inventionFile;
	private Date editionTime;
	private String editionExplan;
	private String abstract_;
	private String history;
	private String indictment;
	private String explan;

	public InventionFileEdition() {
	}

	public InventionFileEdition(int id, User inventor,
			InventionFile inventionFile, Date editionTime,
			String editionExplan, String abstract_, String history,
			String indictment) {
		this.id = id;
		this.editor = inventor;
		this.inventionFile = inventionFile;
		this.editionTime = editionTime;
		this.editionExplan = editionExplan;
		this.abstract_ = abstract_;
		this.history = history;
		this.indictment = indictment;
	}

	

	public InventionFileEdition(InventionFile ifile, User creator) {
		setInventionFile(ifile);
		setEditor(creator);
		ifile.addInventionFileEdition(this);
		creator.addInventionFileEdition(this);
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "editor_id", nullable = false)
	public User getEditor() {
		return this.editor;
	}

	public void setEditor(User inventor) {
		this.editor = inventor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "invention_file_id", nullable = false)
	public InventionFile getInventionFile() {
		return this.inventionFile;
	}

	public void setInventionFile(InventionFile inventionFile) {
		this.inventionFile = inventionFile;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edition_time", nullable = false, length = 19)
	public Date getEditionTime() {
		return this.editionTime;
	}

	public void setEditionTime(Date editionTime) {
		this.editionTime = editionTime;
	}

	@Column(name = "edition_explan", nullable = false, length = 65535)
	public String getEditionExplan() {
		return this.editionExplan;
	}

	public void setEditionExplan(String editionExplan) {
		this.editionExplan = editionExplan;
	}

	@Column(name = "abstract", nullable = false, length = 65535)
	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}
	

	@Column(name = "history", nullable = false, length = 65535)
	public String getHistory() {
		return this.history;
	}

	public void setHistory(String history) {
		this.history = history;
	}

	@Column(name = "indictment", nullable = false, length = 65535)
	public String getIndictment() {
		return this.indictment;
	}

	public void setIndictment(String indictment) {
		this.indictment = indictment;
	}
	
	
	@Column(name = "explan", nullable = false, length = 65535)
	public String getExplan() {
		return this.explan;
	}

	public void setExplan(String explan) {
		this.explan = explan;
	}

	@Override
	public String[] showRowRepresentation(String type) {
		return new String[]{getEditor().getFullName(),getEditionTime().toString(),getEditionExplan()};
	}

	public static String[] getColumnNames() {
		return new String[] {  "ثبت کننده ویرایش","تاریخ ویرایش","توضیح ویرایش"};
	}
	
	

}
