package invention;

// Generated Jul 31, 2012 6:27:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import user.User;
import util.TableRowRepresentation;

/**
 * InventionFileAssesment generated by hbm2java
 */
@Entity
@Table(name = "invention_file_assesment", catalog = "patentsys")
public class InventionFileAssesment implements java.io.Serializable,
		TableRowRepresentation {

	private int id;
	private User expert;
	private Invention invention;
	private Date assignTime;
	private Date finishTime;
	private Boolean originality;
	private Boolean abstractCompleteness;
	private Boolean docCompleteness;
	private Boolean indictmentConsistency;
	private Boolean representationCheck;

	public InventionFileAssesment() {

	}

	public InventionFileAssesment(int id, User expert, Invention invention,
			Date assignTime) {
		this.id = id;
		this.expert = expert;
		this.invention = invention;
		this.assignTime = assignTime;
	}

	public InventionFileAssesment(int id, User expert, Invention invention,
			Date assignTime, Date finishTime, Boolean originality,
			Boolean abstractCompleteness, Boolean docCompleteness,
			Boolean indictmentConsistency, Boolean representationCheck) {
		this.id = id;
		this.expert = expert;
		this.invention = invention;
		this.assignTime = assignTime;
		this.finishTime = finishTime;
		this.originality = originality;
		this.abstractCompleteness = abstractCompleteness;
		this.docCompleteness = docCompleteness;
		this.indictmentConsistency = indictmentConsistency;
		this.representationCheck = representationCheck;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "expert_id", nullable = false)
	public User getExpert() {
		return this.expert;
	}

	public void setExpert(User expert) {
		this.expert = expert;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "invention_id", nullable = false)
	public Invention getInvention() {
		return this.invention;
	}

	public void setInvention(Invention invention) {
		this.invention = invention;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "assign_time", nullable = false, length = 19)
	public Date getAssignTime() {
		return this.assignTime;
	}

	public void setAssignTime(Date assignTime) {
		this.assignTime = assignTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "finish_time", length = 19)
	public Date getFinishTime() {
		return this.finishTime;
	}

	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	@Column(name = "originality")
	public Boolean getOriginality() {
		return this.originality;
	}

	public void setOriginality(Boolean originality) {
		this.originality = originality;
	}

	@Column(name = "abstract_completeness")
	public Boolean getAbstractCompleteness() {
		return this.abstractCompleteness;
	}

	public void setAbstractCompleteness(Boolean abstractCompleteness) {
		this.abstractCompleteness = abstractCompleteness;
	}

	@Column(name = "doc_completeness")
	public Boolean getDocCompleteness() {
		return this.docCompleteness;
	}

	public void setDocCompleteness(Boolean docCompleteness) {
		this.docCompleteness = docCompleteness;
	}

	@Column(name = "indictment_consistency")
	public Boolean getIndictmentConsistency() {
		return this.indictmentConsistency;
	}

	public void setIndictmentConsistency(Boolean indictmentConsistency) {
		this.indictmentConsistency = indictmentConsistency;
	}

	@Column(name = "representation_check")
	public Boolean getRepresentationCheck() {
		return this.representationCheck;
	}

	public void setRepresentationCheck(Boolean representationCheck) {
		this.representationCheck = representationCheck;
	}

	@Override
	public String[] showRowRepresentation(String type) {
		return new String[] {
				getInvention().getInventionFile().getCreator().getFullName(),
				getInvention().getInventionFile().getTitle(),
				getAssignTime().toString() };
	}

	@Transient
	public static String[] getColumnNames() {
		return new String[] { "نام اختراع", "نام کاربر متقاضی",
				"تاریخ ارسال برای ارزیابی" };
	}

	public boolean checkAllTrue() {
		return (getRepresentationCheck() && getOriginality()
				&& getAbstractCompleteness() && getDocCompleteness() && getIndictmentConsistency());
	}

}
