package invention;

// Generated Jul 31, 2012 6:27:12 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import user.User;
import util.TableRowRepresentation;

/**
 * InventorCollaboration generated by hbm2java
 */
@Entity
@Table(name = "inventor_collaboration", catalog = "patentsys")
public class InventorCollaboration implements java.io.Serializable, TableRowRepresentation {

	private int id;
	private User inventor;
	private InventionFile inventionFile;
	private double financialShare;
	private double spiritualShare;

	public InventorCollaboration() {
	}

	public InventorCollaboration(User inventor,
			InventionFile inventionFile, double financialShare,
			double spiritualShare) {
		this.inventor = inventor;
		this.inventionFile = inventionFile;
		this.financialShare = financialShare;
		this.spiritualShare = spiritualShare;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "inventor_id", nullable = false)
	public User getInventor() {
		return this.inventor;
	}

	public void setInventor(User inventor) {
		this.inventor = inventor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "invention_file_id", nullable = false)
	public InventionFile getInventionFile() {
		return this.inventionFile;
	}

	public void setInventionFile(InventionFile inventionFile) {
		this.inventionFile = inventionFile;
	}

	@Column(name = "financial_share", nullable = false, precision = 22, scale = 0)
	public Double getFinancialShare() {
		return this.financialShare;
	}

	public void setFinancialShare(double financialShare) {
		this.financialShare = financialShare;
	}

	@Column(name = "spiritual_share", nullable = false, precision = 22, scale = 0)
	public Double getSpiritualShare() {
		return this.spiritualShare;
	}

	public void setSpiritualShare(double spiritualShare) {
		this.spiritualShare = spiritualShare;
	}

	@Override
	public String[] showRowRepresentation(String type) {
		return new String[]{getInventor().getFullName(),getFinancialShare().toString(),getSpiritualShare().toString()};
	}

	public static String[] getColumnNames(String string) {
		if(string==null)
			return new String[]{"نام مخترع","مالکیت مادی","مالکیت معنوی"};
		else
			return new String[]{"نام مخترع","مالکیت مادی","مالکیت معنوی"};
	}

	public void setSpiritualShareAndUpdate(Double value) throws Exception {
		if(value>100 || value<0)
			throw new Exception();
		else{
			setSpiritualShare(value);
			for(InventorCollaboration ic: getInventionFile().getInventorCollaborations()){
				if(ic!=this)
					ic.setSpiritualShare((100.0-value)/(getInventionFile().getInventorCollaborations().size()-1));
			}
		}
		
	}

	public void setFinancialShareAndUpdate(Double value) throws Exception {
		if(value>100 || value<0)
			throw new Exception();
		else{
			setFinancialShare(value);
			for(InventorCollaboration ic: getInventionFile().getInventorCollaborations()){
				if(ic!=this)
					ic.setFinancialShare((100.0-value)/(getInventionFile().getInventorCollaborations().size()-1));
			}
		}
		
	}

}
