generator:
  class: sfPropelGenerator
  param:
    model_class:           Article
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Article
    plural:                Articles
    route_prefix:          article
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
         display:        [title, summary, nb_comments, tag, created_at]
         fields:
           content:  { params: size=10 }

               
      filter:
         display:        [title, content, created_at, tag, _adminSlot]
      form:
          display:       [title, content, tag, _adminSlot]
      edit:
        display:        [title, content, tag, _adminSlot]
      new:
        display:        [title, content, tag, _adminSlot]