package util;

// Generated Aug 3, 2012 5:36:24 AM by Hibernate Tools 4.0.0

import invention.InventionFile;

import java.io.File;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "patentsys")
public class Attachment implements java.io.Serializable, TableRowRepresentation {

	private Integer id;
	private InventionFile inventionFile;
	private String filename;
	private Date attachtime;
	private String extension;
	private Integer size;
	
	public enum Status{
		added,
		saved,
		removed;
	};
	
	private Status status;

	@Column(name = "status", nullable = false)
	@Enumerated(EnumType.ORDINAL) 
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Transient
	private File file;

	@Column(name = "extension", length = 10)
	public String getExtension() {
		return extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Transient
	public File getFile() {
		return file;
	}

	public Attachment() {
	}

	public Attachment(String filename, Date attachtime) {
		this.filename = filename;
		this.attachtime = attachtime;
	}

	public Attachment(InventionFile inventionFile, String filename,
			Date attachtime) {
		this.inventionFile = inventionFile;
		this.filename = filename;
		this.attachtime = attachtime;
	}

	@Column(name = "size")
	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	public Attachment(String filename, File file) {
		this.file = file;
		this.filename = filename;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "invention_file_id")
	public InventionFile getInventionFile() {
		return this.inventionFile;
	}

	public void setInventionFile(InventionFile inventionFile) {
		this.inventionFile = inventionFile;
	}

	@Column(name = "filename", nullable = false, length = 200)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "attachtime", nullable = false, length = 19)
	public Date getAttachtime() {
		return this.attachtime;
	}

	public void setAttachtime(Date attachtime) {
		this.attachtime = attachtime;
	}

	@Override
	public String[] showRowRepresentation(String type) {
		String sizestr="نا مشخص";
	
		if(getSize()!=null)
			sizestr=getSize().toString();
		
		return new String[] { getFilename(),sizestr };
	}

	public static String[] getColumnNames(String type) {
		return new String[] { "نام فایل","حجم"};
	}

}
