package user;

// Generated Jul 31, 2012 6:27:12 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import util.Attachment;
import util.TableRowRepresentation;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", catalog = "patentsys", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Company implements java.io.Serializable, TableRowRepresentation {

	private Integer id;
	private Attachment attachment;
	private String name;
	private String address;
	private Long phoneNumber;

	public Company() {
	}

	public Company(Attachment attachment, String name) {
		this.attachment = attachment;
		this.name = name;
	}

	public Company(Attachment attachment, String name, String address,
			Long phoneNumber) {
		this.attachment = attachment;
		this.name = name;
		this.address = address;
		this.phoneNumber = phoneNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "introduce_file_id", nullable = false)
	public Attachment getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	@Column(name = "name", unique = true, nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phoneNumber")
	public Long getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Long phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Override
	public String[] showRowRepresentation(String type) {
		// TODO Auto-generated method stub
		return null;
	}

}
