propel:
  blog_article:
    _attributes: { phpName: Article }
    id:
    title:        varchar(255)
    content:      longvarchar
    created_at:
    tag:          varchar
  blog_comment:
    _attributes: { phpName: Comment }
    id:
    article_id:
    author:       varchar(255)
    content:      longvarchar
    created_at: